### PR TITLE
Add Servo's `style` crate as a benchmark

### PR DESCRIPTION
**Pull request by alexcrichton**
This PR adds the `style` crate to this repository to start collecting benchmark data for. The steps taken to do this were:

* Import the `components` directory of the [servo repository](https://github.com/servo/servo/) at servo/servo@9b276565
* Fix the build script to compile
* Add configuration to compile Servo
* Add patches that represent subsequent commits after servo/servo@9b276565 as incremental changes

It looks like enabling incremental emits tons of "Quasi-quoting might make incremental compilation very inefficient: (NtExpr(..), None)" warnings and indeed the incremental compilation is so slow I've disabled it for now. Hopefully we can at least start collecting data for absolute compile times!

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
This currently adds quite a lot of run time to the benchmarks -- 17 minutes on Travis, which is likely closer to 45 or so on the AWS machine. I'm somewhat concerned about that, since while it's not technically problematic since we'll still keep up with the queue, it is getting rather long. After this, I expect tests on the AWS machine to take upwards of 1.5 hours, which is too long for my liking. Otherwise, though, this looks good to me. I don't think that we can really slim this down much, right?

**Comment by alexcrichton** [comment]
Maybe @michaelwoerister or @nikomatsakis would have some more to say to that effect? This PR was [requested this morning](https://botbot.me/mozilla/rustc/2017-07-25/?msg=89024521&page=1).

We can look into allocating a larger instance for perf collection as well if need be, although that'd invalidate historical data.

**Comment by alexcrichton** [comment]
Also in terms of slimming down, I think the point of this benchmark is to be "real world" what Servo is experiencing, so in that sense trying to reduce it may defeat the purpose.

**Comment by Mark-Simulacrum** [comment]
Yeah, I see the reasoning behind not wanting to slim this down. I'm fine with merging as-is, just slightly worried (especially about eventually adding incremental benchmarks) in terms of the time cost.

**Comment by Mark-Simulacrum** [comment]
I've decided that we might as well merge and at least start getting data on this. It's still hopefully within our ~2 hour window of time we have to finish, so in theory at least doesn't hurt us too much...

**Pull request merged**
