### PR TITLE
Add a new "small" tokio benchmark

### PR DESCRIPTION
**Pull request by alexcrichton**
I've been working on this locally and the file added here takes 5-7s iteslf to
compile which I found surprising in terms of slowness. I was then encouraged to
upstream the benchmark here for tracking!

### CODE REVIEW

**Comment by aturon** [comment]
@michaelwoerister @nikomatsakis this is an interesting case, since for this small file:

- Incremental mode creates 150 LLVM modules
- Unchanged incremental build takes 2s
- Any changes shoots it back up to ~7s
- Linking takes 0.5s
- Type checking is pretty trivial

It seems worth digging into this. For one thing, we need to be getting better baseline performance for futures to be a viable foundation for I/O.

**Comment by Mark-Simulacrum** [comment]
I'm guessing we may want to add some patches here to test the incremental portion. Once this merges, it should be straightforward to pull it down on the collection server, at which point we'll automatically back-collect data since January. Feel free to merge when ready (if you can, not sure).

**Comment by alexcrichton** [comment]
@Mark-Simulacrum does that look right?

**Comment by Mark-Simulacrum** [comment]
Yep, looks good to me!

**Pull request merged**
